// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	"github.com/phogolabs/cli"
)

type Converter struct {
	ConvertStub        func(interface{}) (interface{}, error)
	convertMutex       sync.RWMutex
	convertArgsForCall []struct {
		arg1 interface{}
	}
	convertReturns struct {
		result1 interface{}
		result2 error
	}
	convertReturnsOnCall map[int]struct {
		result1 interface{}
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Converter) Convert(arg1 interface{}) (interface{}, error) {
	fake.convertMutex.Lock()
	ret, specificReturn := fake.convertReturnsOnCall[len(fake.convertArgsForCall)]
	fake.convertArgsForCall = append(fake.convertArgsForCall, struct {
		arg1 interface{}
	}{arg1})
	fake.recordInvocation("Convert", []interface{}{arg1})
	fake.convertMutex.Unlock()
	if fake.ConvertStub != nil {
		return fake.ConvertStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.convertReturns.result1, fake.convertReturns.result2
}

func (fake *Converter) ConvertCallCount() int {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	return len(fake.convertArgsForCall)
}

func (fake *Converter) ConvertArgsForCall(i int) interface{} {
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	return fake.convertArgsForCall[i].arg1
}

func (fake *Converter) ConvertReturns(result1 interface{}, result2 error) {
	fake.ConvertStub = nil
	fake.convertReturns = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *Converter) ConvertReturnsOnCall(i int, result1 interface{}, result2 error) {
	fake.ConvertStub = nil
	if fake.convertReturnsOnCall == nil {
		fake.convertReturnsOnCall = make(map[int]struct {
			result1 interface{}
			result2 error
		})
	}
	fake.convertReturnsOnCall[i] = struct {
		result1 interface{}
		result2 error
	}{result1, result2}
}

func (fake *Converter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.convertMutex.RLock()
	defer fake.convertMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Converter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cli.Converter = new(Converter)
